/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GuestFeedbackRouteImport } from './routes/guest-feedback'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedPeerFeedbackRouteImport } from './routes/_authenticated/peer-feedback'
import { Route as AuthenticatedReflectionsRouteImport } from './routes/_authenticated/reflections'
import { Route as AuthenticatedRotaRouteImport } from './routes/_authenticated/rota'
import { Route as AuthenticatedSwapsRouteImport } from './routes/_authenticated/swaps'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAdministratorsRouteImport } from './routes/_authenticated/admin/administrators'
import { Route as AuthenticatedAdminFacultyRouteImport } from './routes/_authenticated/admin/faculty'
import { Route as AuthenticatedAdminFellowsRouteImport } from './routes/_authenticated/admin/fellows'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminLeaveRouteImport } from './routes/_authenticated/admin/leave'
import { Route as AuthenticatedAdminQualityRouteImport } from './routes/_authenticated/admin/quality'
import { Route as AuthenticatedAdminReflectionsRouteImport } from './routes/_authenticated/admin/reflections'
import { Route as AuthenticatedAdminRoomsRouteImport } from './routes/_authenticated/admin/rooms'
import { Route as AuthenticatedAdminSwapsRouteImport } from './routes/_authenticated/admin/swaps'
import { Route as AuthenticatedAdminTeachingRouteImport } from './routes/_authenticated/admin/teaching'
import { Route as ApiPublicGuestFeedbackRouteImport } from './routes/api/public/guest-feedback'
import { Route as AuthenticatedAdminLeaveIndexRouteImport } from './routes/_authenticated/admin/leave/index'
import { Route as AuthenticatedAdminLeaveDecisionsRouteImport } from './routes/_authenticated/admin/leave/decisions'
import { Route as AuthenticatedAdminLeaveOverridesRouteImport } from './routes/_authenticated/admin/leave/overrides'
import { Route as AuthenticatedAdminLeavePendingRouteImport } from './routes/_authenticated/admin/leave/pending'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestFeedbackRoute = GuestFeedbackRouteImport.update({
  id: '/guest-feedback',
  path: '/guest-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeerFeedbackRoute =
  AuthenticatedPeerFeedbackRouteImport.update({
    id: '/peer-feedback',
    path: '/peer-feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReflectionsRoute =
  AuthenticatedReflectionsRouteImport.update({
    id: '/reflections',
    path: '/reflections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRotaRoute = AuthenticatedRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSwapsRoute = AuthenticatedSwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdministratorsRoute =
  AuthenticatedAdminAdministratorsRouteImport.update({
    id: '/administrators',
    path: '/administrators',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFacultyRoute =
  AuthenticatedAdminFacultyRouteImport.update({
    id: '/faculty',
    path: '/faculty',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFellowsRoute =
  AuthenticatedAdminFellowsRouteImport.update({
    id: '/fellows',
    path: '/fellows',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeaveRoute = AuthenticatedAdminLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQualityRoute =
  AuthenticatedAdminQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReflectionsRoute =
  AuthenticatedAdminReflectionsRouteImport.update({
    id: '/reflections',
    path: '/reflections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRoomsRoute = AuthenticatedAdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSwapsRoute = AuthenticatedAdminSwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTeachingRoute =
  AuthenticatedAdminTeachingRouteImport.update({
    id: '/teaching',
    path: '/teaching',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicGuestFeedbackRoute = ApiPublicGuestFeedbackRouteImport.update({
  id: '/api/public/guest-feedback',
  path: '/api/public/guest-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminLeaveIndexRoute =
  AuthenticatedAdminLeaveIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminLeaveRoute,
  } as any)
const AuthenticatedAdminLeaveDecisionsRoute =
  AuthenticatedAdminLeaveDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => AuthenticatedAdminLeaveRoute,
  } as any)
const AuthenticatedAdminLeaveOverridesRoute =
  AuthenticatedAdminLeaveOverridesRouteImport.update({
    id: '/overrides',
    path: '/overrides',
    getParentRoute: () => AuthenticatedAdminLeaveRoute,
  } as any)
const AuthenticatedAdminLeavePendingRoute =
  AuthenticatedAdminLeavePendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedAdminLeaveRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest-feedback': typeof GuestFeedbackRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/connect': typeof AuthenticatedConnectRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/peer-feedback': typeof AuthenticatedPeerFeedbackRoute
  '/reflections': typeof AuthenticatedReflectionsRoute
  '/rota': typeof AuthenticatedRotaRoute
  '/swaps': typeof AuthenticatedSwapsRoute
  '/admin/administrators': typeof AuthenticatedAdminAdministratorsRoute
  '/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/admin/fellows': typeof AuthenticatedAdminFellowsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/leave': typeof AuthenticatedAdminLeaveRouteWithChildren
  '/admin/quality': typeof AuthenticatedAdminQualityRoute
  '/admin/reflections': typeof AuthenticatedAdminReflectionsRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/swaps': typeof AuthenticatedAdminSwapsRoute
  '/admin/teaching': typeof AuthenticatedAdminTeachingRoute
  '/api/public/guest-feedback': typeof ApiPublicGuestFeedbackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/leave/decisions': typeof AuthenticatedAdminLeaveDecisionsRoute
  '/admin/leave/overrides': typeof AuthenticatedAdminLeaveOverridesRoute
  '/admin/leave/pending': typeof AuthenticatedAdminLeavePendingRoute
  '/admin/leave/': typeof AuthenticatedAdminLeaveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest-feedback': typeof GuestFeedbackRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/peer-feedback': typeof AuthenticatedPeerFeedbackRoute
  '/reflections': typeof AuthenticatedReflectionsRoute
  '/rota': typeof AuthenticatedRotaRoute
  '/swaps': typeof AuthenticatedSwapsRoute
  '/admin/administrators': typeof AuthenticatedAdminAdministratorsRoute
  '/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/admin/fellows': typeof AuthenticatedAdminFellowsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/quality': typeof AuthenticatedAdminQualityRoute
  '/admin/reflections': typeof AuthenticatedAdminReflectionsRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/swaps': typeof AuthenticatedAdminSwapsRoute
  '/admin/teaching': typeof AuthenticatedAdminTeachingRoute
  '/api/public/guest-feedback': typeof ApiPublicGuestFeedbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/leave/decisions': typeof AuthenticatedAdminLeaveDecisionsRoute
  '/admin/leave/overrides': typeof AuthenticatedAdminLeaveOverridesRoute
  '/admin/leave/pending': typeof AuthenticatedAdminLeavePendingRoute
  '/admin/leave': typeof AuthenticatedAdminLeaveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest-feedback': typeof GuestFeedbackRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/peer-feedback': typeof AuthenticatedPeerFeedbackRoute
  '/_authenticated/reflections': typeof AuthenticatedReflectionsRoute
  '/_authenticated/rota': typeof AuthenticatedRotaRoute
  '/_authenticated/swaps': typeof AuthenticatedSwapsRoute
  '/_authenticated/admin/administrators': typeof AuthenticatedAdminAdministratorsRoute
  '/_authenticated/admin/faculty': typeof AuthenticatedAdminFacultyRoute
  '/_authenticated/admin/fellows': typeof AuthenticatedAdminFellowsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/leave': typeof AuthenticatedAdminLeaveRouteWithChildren
  '/_authenticated/admin/quality': typeof AuthenticatedAdminQualityRoute
  '/_authenticated/admin/reflections': typeof AuthenticatedAdminReflectionsRoute
  '/_authenticated/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/_authenticated/admin/swaps': typeof AuthenticatedAdminSwapsRoute
  '/_authenticated/admin/teaching': typeof AuthenticatedAdminTeachingRoute
  '/api/public/guest-feedback': typeof ApiPublicGuestFeedbackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/leave/decisions': typeof AuthenticatedAdminLeaveDecisionsRoute
  '/_authenticated/admin/leave/overrides': typeof AuthenticatedAdminLeaveOverridesRoute
  '/_authenticated/admin/leave/pending': typeof AuthenticatedAdminLeavePendingRoute
  '/_authenticated/admin/leave/': typeof AuthenticatedAdminLeaveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/guest-feedback'
    | '/mcp'
    | '/reset-password'
    | '/admin'
    | '/connect'
    | '/dashboard'
    | '/help'
    | '/leave'
    | '/peer-feedback'
    | '/reflections'
    | '/rota'
    | '/swaps'
    | '/admin/administrators'
    | '/admin/faculty'
    | '/admin/fellows'
    | '/admin/import'
    | '/admin/leave'
    | '/admin/quality'
    | '/admin/reflections'
    | '/admin/rooms'
    | '/admin/swaps'
    | '/admin/teaching'
    | '/api/public/guest-feedback'
    | '/admin/'
    | '/admin/leave/decisions'
    | '/admin/leave/overrides'
    | '/admin/leave/pending'
    | '/admin/leave/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/guest-feedback'
    | '/mcp'
    | '/reset-password'
    | '/connect'
    | '/dashboard'
    | '/help'
    | '/leave'
    | '/peer-feedback'
    | '/reflections'
    | '/rota'
    | '/swaps'
    | '/admin/administrators'
    | '/admin/faculty'
    | '/admin/fellows'
    | '/admin/import'
    | '/admin/quality'
    | '/admin/reflections'
    | '/admin/rooms'
    | '/admin/swaps'
    | '/admin/teaching'
    | '/api/public/guest-feedback'
    | '/admin'
    | '/admin/leave/decisions'
    | '/admin/leave/overrides'
    | '/admin/leave/pending'
    | '/admin/leave'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/guest-feedback'
    | '/mcp'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/connect'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/leave'
    | '/_authenticated/peer-feedback'
    | '/_authenticated/reflections'
    | '/_authenticated/rota'
    | '/_authenticated/swaps'
    | '/_authenticated/admin/administrators'
    | '/_authenticated/admin/faculty'
    | '/_authenticated/admin/fellows'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/leave'
    | '/_authenticated/admin/quality'
    | '/_authenticated/admin/reflections'
    | '/_authenticated/admin/rooms'
    | '/_authenticated/admin/swaps'
    | '/_authenticated/admin/teaching'
    | '/api/public/guest-feedback'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/leave/decisions'
    | '/_authenticated/admin/leave/overrides'
    | '/_authenticated/admin/leave/pending'
    | '/_authenticated/admin/leave/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuestFeedbackRoute: typeof GuestFeedbackRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicGuestFeedbackRoute: typeof ApiPublicGuestFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-feedback': {
      id: '/guest-feedback'
      path: '/guest-feedback'
      fullPath: '/guest-feedback'
      preLoaderRoute: typeof GuestFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/peer-feedback': {
      id: '/_authenticated/peer-feedback'
      path: '/peer-feedback'
      fullPath: '/peer-feedback'
      preLoaderRoute: typeof AuthenticatedPeerFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reflections': {
      id: '/_authenticated/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof AuthenticatedReflectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rota': {
      id: '/_authenticated/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof AuthenticatedRotaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/swaps': {
      id: '/_authenticated/swaps'
      path: '/swaps'
      fullPath: '/swaps'
      preLoaderRoute: typeof AuthenticatedSwapsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/administrators': {
      id: '/_authenticated/admin/administrators'
      path: '/administrators'
      fullPath: '/admin/administrators'
      preLoaderRoute: typeof AuthenticatedAdminAdministratorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faculty': {
      id: '/_authenticated/admin/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AuthenticatedAdminFacultyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fellows': {
      id: '/_authenticated/admin/fellows'
      path: '/fellows'
      fullPath: '/admin/fellows'
      preLoaderRoute: typeof AuthenticatedAdminFellowsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leave': {
      id: '/_authenticated/admin/leave'
      path: '/leave'
      fullPath: '/admin/leave'
      preLoaderRoute: typeof AuthenticatedAdminLeaveRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quality': {
      id: '/_authenticated/admin/quality'
      path: '/quality'
      fullPath: '/admin/quality'
      preLoaderRoute: typeof AuthenticatedAdminQualityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reflections': {
      id: '/_authenticated/admin/reflections'
      path: '/reflections'
      fullPath: '/admin/reflections'
      preLoaderRoute: typeof AuthenticatedAdminReflectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rooms': {
      id: '/_authenticated/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AuthenticatedAdminRoomsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/swaps': {
      id: '/_authenticated/admin/swaps'
      path: '/swaps'
      fullPath: '/admin/swaps'
      preLoaderRoute: typeof AuthenticatedAdminSwapsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teaching': {
      id: '/_authenticated/admin/teaching'
      path: '/teaching'
      fullPath: '/admin/teaching'
      preLoaderRoute: typeof AuthenticatedAdminTeachingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/guest-feedback': {
      id: '/api/public/guest-feedback'
      path: '/api/public/guest-feedback'
      fullPath: '/api/public/guest-feedback'
      preLoaderRoute: typeof ApiPublicGuestFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/leave/': {
      id: '/_authenticated/admin/leave/'
      path: '/'
      fullPath: '/admin/leave/'
      preLoaderRoute: typeof AuthenticatedAdminLeaveIndexRouteImport
      parentRoute: typeof AuthenticatedAdminLeaveRoute
    }
    '/_authenticated/admin/leave/decisions': {
      id: '/_authenticated/admin/leave/decisions'
      path: '/decisions'
      fullPath: '/admin/leave/decisions'
      preLoaderRoute: typeof AuthenticatedAdminLeaveDecisionsRouteImport
      parentRoute: typeof AuthenticatedAdminLeaveRoute
    }
    '/_authenticated/admin/leave/overrides': {
      id: '/_authenticated/admin/leave/overrides'
      path: '/overrides'
      fullPath: '/admin/leave/overrides'
      preLoaderRoute: typeof AuthenticatedAdminLeaveOverridesRouteImport
      parentRoute: typeof AuthenticatedAdminLeaveRoute
    }
    '/_authenticated/admin/leave/pending': {
      id: '/_authenticated/admin/leave/pending'
      path: '/pending'
      fullPath: '/admin/leave/pending'
      preLoaderRoute: typeof AuthenticatedAdminLeavePendingRouteImport
      parentRoute: typeof AuthenticatedAdminLeaveRoute
    }
  }
}

interface AuthenticatedAdminLeaveRouteChildren {
  AuthenticatedAdminLeaveDecisionsRoute: typeof AuthenticatedAdminLeaveDecisionsRoute
  AuthenticatedAdminLeaveOverridesRoute: typeof AuthenticatedAdminLeaveOverridesRoute
  AuthenticatedAdminLeavePendingRoute: typeof AuthenticatedAdminLeavePendingRoute
  AuthenticatedAdminLeaveIndexRoute: typeof AuthenticatedAdminLeaveIndexRoute
}

const AuthenticatedAdminLeaveRouteChildren: AuthenticatedAdminLeaveRouteChildren =
  {
    AuthenticatedAdminLeaveDecisionsRoute:
      AuthenticatedAdminLeaveDecisionsRoute,
    AuthenticatedAdminLeaveOverridesRoute:
      AuthenticatedAdminLeaveOverridesRoute,
    AuthenticatedAdminLeavePendingRoute: AuthenticatedAdminLeavePendingRoute,
    AuthenticatedAdminLeaveIndexRoute: AuthenticatedAdminLeaveIndexRoute,
  }

const AuthenticatedAdminLeaveRouteWithChildren =
  AuthenticatedAdminLeaveRoute._addFileChildren(
    AuthenticatedAdminLeaveRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdministratorsRoute: typeof AuthenticatedAdminAdministratorsRoute
  AuthenticatedAdminFacultyRoute: typeof AuthenticatedAdminFacultyRoute
  AuthenticatedAdminFellowsRoute: typeof AuthenticatedAdminFellowsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminLeaveRoute: typeof AuthenticatedAdminLeaveRouteWithChildren
  AuthenticatedAdminQualityRoute: typeof AuthenticatedAdminQualityRoute
  AuthenticatedAdminReflectionsRoute: typeof AuthenticatedAdminReflectionsRoute
  AuthenticatedAdminRoomsRoute: typeof AuthenticatedAdminRoomsRoute
  AuthenticatedAdminSwapsRoute: typeof AuthenticatedAdminSwapsRoute
  AuthenticatedAdminTeachingRoute: typeof AuthenticatedAdminTeachingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdministratorsRoute: AuthenticatedAdminAdministratorsRoute,
  AuthenticatedAdminFacultyRoute: AuthenticatedAdminFacultyRoute,
  AuthenticatedAdminFellowsRoute: AuthenticatedAdminFellowsRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminLeaveRoute: AuthenticatedAdminLeaveRouteWithChildren,
  AuthenticatedAdminQualityRoute: AuthenticatedAdminQualityRoute,
  AuthenticatedAdminReflectionsRoute: AuthenticatedAdminReflectionsRoute,
  AuthenticatedAdminRoomsRoute: AuthenticatedAdminRoomsRoute,
  AuthenticatedAdminSwapsRoute: AuthenticatedAdminSwapsRoute,
  AuthenticatedAdminTeachingRoute: AuthenticatedAdminTeachingRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedPeerFeedbackRoute: typeof AuthenticatedPeerFeedbackRoute
  AuthenticatedReflectionsRoute: typeof AuthenticatedReflectionsRoute
  AuthenticatedRotaRoute: typeof AuthenticatedRotaRoute
  AuthenticatedSwapsRoute: typeof AuthenticatedSwapsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedPeerFeedbackRoute: AuthenticatedPeerFeedbackRoute,
  AuthenticatedReflectionsRoute: AuthenticatedReflectionsRoute,
  AuthenticatedRotaRoute: AuthenticatedRotaRoute,
  AuthenticatedSwapsRoute: AuthenticatedSwapsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuestFeedbackRoute: GuestFeedbackRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicGuestFeedbackRoute: ApiPublicGuestFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
